name: Code Deploy 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

env:
  ARTIFACT_NAME: userAddLamda
  AWS_REGION: us-east-1
  
jobs:
  lamda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Deployment artifacts
        run: |
          zip -r ${{ env.ARTIFACT_NAME }} index.js

      - name: Copy Artifacts to S3
        run: |
          aws s3 cp ${{ env.ARTIFACT_NAME }}.zip s3://${{secrets.S3_BUCKET}}

      - name: Update lambdaFunction code
        run: |
          aws lambda update-function-code --function-name userAddLambda --s3-bucket ${{secrets.S3_BUCKET}} --s3-key ${{ env.ARTIFACT_NAME }}.zip